# problem1

In [39]:
import numpy as np
import sympy
import matplotlib.pyplot as plt
%matplotlib inline

v1 = np.array([1, 0, 1, 2])
v2 = np.array([2, 1, 4, 11])
v3 = np.array([3, 0, 3, 6])
v4 = np.array([4, 1, 6, 15])
orig_mat = np.matrix([v1, v2, v3, v4])

v1 = np.array([1, 0, 1, 2, 4])
v2 = np.array([2, 1, 4, 11, 18])
v3 = np.array([3, 0, 3, 6, 12])
v4 = np.array([4, 1, 6, 15, 26])
inspan_mat = np.matrix([v1, v2, v3, v4])

v1 = np.array([1, 0, 1, 2, 1])
v2 = np.array([2, 1, 4, 11, 3])
v3 = np.array([3, 0, 3, 6, 1])
v4 = np.array([4, 1, 6, 15, 4])
nonspan_mat = np.matrix([v1, v2, v3, v4])

orig_reduced = sympy.Matrix(orig_mat).rref()
inspan_reduced = sympy.Matrix(inspan_mat).rref()
nonspan_reduced = sympy.Matrix(nonspan_mat).rref()
print ("Original pivot rows: ",len(orig_reduced[1]))
print ("Matrix 1 pivot rows: ",len(inspan_reduced[1]))
print ("Matrix 2 pivot rows: ",len(nonspan_reduced[1]))


Original pivot rows:  2
Matrix 1 pivot rows:  2
Matrix 2 pivot rows:  3


By making augmented matrixes, from result shown, inspan matrix does not add more pivot rows, however, not inspan matrix add more pivot rows.

1B

In [42]:
rank = len(orig_reduced[1])
print("Subspace rank of matrix: ",rank," for \n{}".format(orig_mat))


Subspace rank of matrix:  2  for 
[[ 1  0  1  2]
 [ 2  1  4 11]
 [ 3  0  3  6]
 [ 4  1  6 15]]


1C

In [45]:
q,r = np.linalg.qr(orig_mat.T)
print(q)
print(r)
orthonormal_basis = q[:, :rank]
print('Orthonormal Basis:\n',orthonormal_basis)

[[-0.40824829  0.79211803  0.45374261  0.        ]
 [-0.         -0.29704426  0.51856298 -0.80178373]
 [-0.40824829  0.19802951 -0.7130241  -0.53452248]
 [-0.81649658 -0.49507377  0.12964074  0.26726124]]
[[ -2.44948974e+00  -1.14309521e+01  -7.34846923e+00  -1.63299316e+01]
 [  0.00000000e+00  -3.36650165e+00   1.72331927e-15  -3.36650165e+00]
 [  0.00000000e+00   0.00000000e+00   9.87155122e-16   9.42460924e-16]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   4.81395150e-17]]
Orthonormal Basis:
 [[-0.40824829  0.79211803]
 [-0.         -0.29704426]
 [-0.40824829  0.19802951]
 [-0.81649658 -0.49507377]]
